/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Control.CAddUser;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Date;
import java.time.LocalDateTime;
/**
 *
 * @author DELL
 */
public class VAddAdminStaff extends javax.swing.JFrame {

    /**
     * Creates new form VAddAdminStaff
     */
    public VAddAdminStaff() {
        initComponents();
    }
    static boolean emailValidator(String email) {
      String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      return email.matches(regex);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type_selector = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        text_fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_nic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        text_password = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_t_no = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        gender_type_selector = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        text_age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_name_with_i = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_add_staff = new javax.swing.JButton();
        lbl_back1 = new javax.swing.JLabel();
        dob_picker = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Admin & Staff");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("ADD STAFF AND ADMIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 440, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        type_selector.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        type_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "staff" }));
        type_selector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                type_selectorItemStateChanged(evt);
            }
        });
        jPanel1.add(type_selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 350, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Full Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        text_fname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 350, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Date Of Birth");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("NIC");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        text_nic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 340, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        text_address.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 860, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        text_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 340, -1));

        text_password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 390, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        text_t_no.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_t_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 340, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Telephone Number");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, -1, -1));

        gender_type_selector.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        gender_type_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(gender_type_selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Select Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        text_age.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(text_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 390, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        text_name_with_i.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_name_with_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_name_with_iActionPerformed(evt);
            }
        });
        jPanel1.add(text_name_with_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 390, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Name With Initials");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        text_id.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_id.setToolTipText("user id");
        jPanel1.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 390, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("User ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 146, 40));

        btn_add_staff.setBackground(new java.awt.Color(204, 0, 0));
        btn_add_staff.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_staff.setText("ADD");
        btn_add_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_staffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 690, 146, 40));

        lbl_back1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_back1.setText("<< Back");
        lbl_back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back1MouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 40));
        jPanel1.add(dob_picker, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 350, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void type_selectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type_selectorItemStateChanged
        CAddUser uselected = new CAddUser();
        text_id.setText(uselected.getNextUserId((String) type_selector.getSelectedItem()));
    }//GEN-LAST:event_type_selectorItemStateChanged
    /*private void formWindowOpened(java.awt.event.WindowEvent evt) {
        CAddUser onload_id = new CAddUser();
        text_id.setText(onload_id.getNextUserId("admin"));
    }*/

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        type_selector.setSelectedIndex(0);
        text_fname.setText("");
        text_name_with_i.setText("");
        dob_picker.setCalendar(null);
        text_age.setText("");
        text_nic.setText("");
        text_address.setText("");
        text_t_no.setText("");
        text_email.setText("");
        text_password.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_add_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_staffActionPerformed
        if(text_fname.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Full Name cannot be blank");
        }
        else if(text_name_with_i.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Name With Initials cannot be blank");
        }
        else if(text_fname.getText().matches("[0-9]+") || text_name_with_i.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Full Name & Name With Initials cannot have numbers");
        }
        else if(dob_picker.getDateEditor().getDate() == null)
        {   JOptionPane.showMessageDialog(null,"Date of birth cannot be blank");
        }
        else if(text_age.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Age cannot be blank");
        }
        else if(!text_age.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Age should be numeric only");
        }
        else if(text_nic.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"NIC cannot be blank");
        }
        else if(text_address.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Address cannot be blank");
        }
        else if(text_t_no.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Phone number cannot be blank");
        }
        else if(!text_t_no.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Phone number should be numeric only");
        }
        else if(text_t_no.getText().length()<10 || text_t_no.getText().length()>10)
        {   JOptionPane.showMessageDialog(null,"Phone number should have 10 numbers");
        }
        else if(text_email.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter Email Address");
        }
        else if(!emailValidator(text_email.getText())==true)
        {   JOptionPane.showMessageDialog(null,"Enter a valid email. Ex:name@gmail.com");
        }
        else if(text_password.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter A Password");
        }
        else if(text_password.getText().length()<8)
        {   JOptionPane.showMessageDialog(null,"Please Enter Password Longer Than 8 Characters");
        }
        else
        {
            String user_type="";
            String id,fname,name_with_i,age,nic,address,t_no,email,password;
            int selected_index_type = type_selector.getSelectedIndex();

            if(selected_index_type == 0)
            {
                user_type = "admin";
            }
            else if(selected_index_type == 1)
            {   user_type = "staff";
            }

            String gender = (String) gender_type_selector.getSelectedItem();
            id = text_id.getText();
            fname = text_fname.getText();
            name_with_i = text_name_with_i.getText();

            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            Date date = dob_picker.getDate();
            String dob = dateFormat.format(date);

            age = text_age.getText();
            nic = text_nic.getText();
            address = text_address.getText();
            t_no = text_t_no.getText();
            email = text_email.getText();
            password = text_password.getText();

            CAddUser userdata = new CAddUser();
            userdata.saveUserData(user_type, id, fname, name_with_i, dob, age, nic, gender, address, t_no, email, password);
        }
    }//GEN-LAST:event_btn_add_staffActionPerformed

    private void text_name_with_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_name_with_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_name_with_iActionPerformed

    private void lbl_back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back1MouseClicked
        try{
            int result;
            FileReader reader1 = new FileReader("UserDetails.txt");
            while ((result=reader1.read())!=-1)
            {   String id;
                id=String.valueOf(result);
                char code=id.charAt(0);
                if(code==('6'))
                {   
                    VAdminDashboard adash = new VAdminDashboard();
                    adash.show();
                    this.dispose();

                }
                else
                {
                    VStaffDashboard adash = new VStaffDashboard();
                    adash.show();
                    this.dispose();
                }
                break;
            }
        }

        catch(FileNotFoundException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(IOException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_back1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CAddUser onload_id = new CAddUser();
        text_id.setText(onload_id.getNextUserId("admin"));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAddAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAddAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAddAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAddAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAddAdminStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_staff;
    private javax.swing.JButton btn_clear;
    private com.toedter.calendar.JDateChooser dob_picker;
    private javax.swing.JComboBox<String> gender_type_selector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_back1;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_age;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_fname;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_name_with_i;
    private javax.swing.JTextField text_nic;
    private javax.swing.JTextField text_password;
    private javax.swing.JTextField text_t_no;
    private javax.swing.JComboBox<String> type_selector;
    // End of variables declaration//GEN-END:variables
}
