/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VAdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public VAdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_addadminstaff = new javax.swing.JButton();
        btn_editadminstaff = new javax.swing.JButton();
        btn_deleteadminstaff = new javax.swing.JButton();
        btn_deletecus = new javax.swing.JButton();
        btn_editcus = new javax.swing.JButton();
        btn_addcus = new javax.swing.JButton();
        btn_viewcus = new javax.swing.JButton();
        btn_viewadminstaff = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Welcome Come to Redna Bank");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 560, 80));

        btn_addadminstaff.setBackground(new java.awt.Color(0, 0, 0));
        btn_addadminstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addadminstaff.setForeground(new java.awt.Color(255, 255, 255));
        btn_addadminstaff.setText("Add Admin  & Staff");
        btn_addadminstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addadminstaffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addadminstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 260, 70));

        btn_editadminstaff.setBackground(new java.awt.Color(0, 0, 0));
        btn_editadminstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_editadminstaff.setForeground(new java.awt.Color(255, 255, 255));
        btn_editadminstaff.setText("Edit Admin & Staff");
        btn_editadminstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editadminstaffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editadminstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 260, 70));

        btn_deleteadminstaff.setBackground(new java.awt.Color(0, 0, 0));
        btn_deleteadminstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_deleteadminstaff.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteadminstaff.setText("Delete Admin & Staff");
        btn_deleteadminstaff.setPreferredSize(new java.awt.Dimension(251, 37));
        btn_deleteadminstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteadminstaffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_deleteadminstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 260, 70));

        btn_deletecus.setBackground(new java.awt.Color(0, 0, 0));
        btn_deletecus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_deletecus.setForeground(new java.awt.Color(255, 255, 255));
        btn_deletecus.setText("Delete Account");
        btn_deletecus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_deletecus, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 260, 70));

        btn_editcus.setBackground(new java.awt.Color(0, 0, 0));
        btn_editcus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_editcus.setForeground(new java.awt.Color(255, 255, 255));
        btn_editcus.setText("Edit Customer");
        btn_editcus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editcusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 260, 70));

        btn_addcus.setBackground(new java.awt.Color(0, 0, 0));
        btn_addcus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addcus.setForeground(new java.awt.Color(255, 255, 255));
        btn_addcus.setText("Add Customer");
        btn_addcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 260, 70));

        btn_viewcus.setBackground(new java.awt.Color(0, 0, 0));
        btn_viewcus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_viewcus.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewcus.setText("View Customer");
        btn_viewcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewcusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_viewcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 260, 70));

        btn_viewadminstaff.setBackground(new java.awt.Color(0, 0, 0));
        btn_viewadminstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_viewadminstaff.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewadminstaff.setText("View Admin & Staff");
        btn_viewadminstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewadminstaffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_viewadminstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 260, 70));

        btn_logout.setBackground(new java.awt.Color(204, 0, 0));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LogOut");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 150, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\NIBM\\1st Year\\EAD\\EAD CW2 Redna Bank\\Redna_Bank\\src\\main\\java\\images\\logofordashboard.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\NIBM\\1st Year\\EAD\\EAD CW2 Redna Bank\\Redna_Bank\\src\\main\\java\\images\\Homebackpic.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editadminstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editadminstaffActionPerformed

        VEditAdminStaff vm = new VEditAdminStaff();
        vm.show();
        this.dispose();
    }//GEN-LAST:event_btn_editadminstaffActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        VLogin l = new VLogin();
        l.show();
        this.dispose();
                    try
                    {
                        char data[]={};
                        FileWriter ft = new FileWriter("UserDetails.txt");
                        ft.write(data);
                        ft.close();
                    }
                    catch(FileNotFoundException ex)
                    {     JOptionPane.showMessageDialog(null,ex.getMessage());  
                    }
                    catch(IOException ex)
                    {       JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
         
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_addadminstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addadminstaffActionPerformed
        VAddAdminStaff va = new VAddAdminStaff();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_addadminstaffActionPerformed

    private void btn_deleteadminstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteadminstaffActionPerformed
        VDeleteAdminAndStaff va = new VDeleteAdminAndStaff();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_deleteadminstaffActionPerformed

    private void btn_addcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcusActionPerformed
        VCustomerAdd va = new VCustomerAdd();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_addcusActionPerformed

    private void btn_editcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editcusActionPerformed
        VUpdateCustomer va = new VUpdateCustomer();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_editcusActionPerformed

    private void btn_deletecusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletecusActionPerformed
        VDeleteAccount va = new VDeleteAccount();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_deletecusActionPerformed

    private void btn_viewcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewcusActionPerformed
        VCustomerDetails va = new VCustomerDetails();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_viewcusActionPerformed

    private void btn_viewadminstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewadminstaffActionPerformed
        VAdminStaffDetails va = new VAdminStaffDetails();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_viewadminstaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addadminstaff;
    private javax.swing.JButton btn_addcus;
    private javax.swing.JButton btn_deleteadminstaff;
    private javax.swing.JButton btn_deletecus;
    private javax.swing.JButton btn_editadminstaff;
    private javax.swing.JButton btn_editcus;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_viewadminstaff;
    private javax.swing.JButton btn_viewcus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
