/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Control.CAdminStaffDetails;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class VAdminStaffDetails extends javax.swing.JFrame {

    /**
     * Creates new form VAdminStaffDetails
     */
    public VAdminStaffDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_view = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmb_type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Staff & Admin");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 204, -1));

        txt_nic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 204, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NIC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        btn_view.setBackground(new java.awt.Color(204, 0, 0));
        btn_view.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_view.setForeground(new java.awt.Color(255, 255, 255));
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 146, 40));

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 146, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NIC", "Gender", "Date of Birth", "Address", "Mobile Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1274, 594));

        cmb_type.setBackground(new java.awt.Color(204, 0, 0));
        cmb_type.setForeground(new java.awt.Color(255, 255, 255));
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Staff" }));
        jPanel1.add(cmb_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 210, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("or");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("VIEW STAFF / ADMIN DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lbl_back2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_back2.setText("<< Back");
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        int option=0;
        if (cmb_type.getSelectedIndex() == 0)//ERROR
        {   JOptionPane.showMessageDialog(null,"Select the Type","Error",0);
        }
        else if (cmb_type.getSelectedIndex() == 1) //Admin
        {
            String sql = null;
            if ((txt_id == null || txt_id.getText().trim().isEmpty()) && (txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                sql="Select * from admin"; option=1;
            }
            else if (!(txt_id == null || txt_id.getText().trim().isEmpty()) && (txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                sql="Select * from admin where AdminId='"+txt_id.getText()+"'"; option=1;
            }
            else if ((txt_id == null || txt_id.getText().trim().isEmpty()) && !(txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                sql="Select * from admin where ANIC='"+txt_nic.getText()+"'"; option=1;
            }
            else //if (!(txt_id == null || txt_id.getText().trim().isEmpty()) && !(txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                JOptionPane.showMessageDialog(null,"Enter Staff ID or NIC to view details");
            }
            switch (option)
            {
                case 0:
                break;

                case 1:
                try
                {   ResultSet rs;
                    CAdminStaffDetails ASdetails=new CAdminStaffDetails();
                    rs=ASdetails.getDetails(sql);
                    while(rs.next())
                    {
                        String id=rs.getString("AdminId");
                        //String full_name=rs.getString("CFullname");
                        String initial_name=rs.getString("AIniName");
                        String nic=rs.getString("ANIC");
                        String gender=rs.getString("AGender");
                        String dob=rs.getString("ADOB");
                        //String age=String.valueOf(rs.getInt("Age"));
                        String address=rs.getString("AdminAddress");
                        String tp_number=String.valueOf(rs.getInt("AdTP"));
                        String email=rs.getString("AdEmail");

                        String tbData[]={id,initial_name,nic,gender,dob,address,tp_number,email};
                        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                        tblModel.addRow(tbData);
                    }

                }
                catch (SQLException e)
                {   JOptionPane.showMessageDialog(null, e.getMessage());
                }
                catch (Exception e)
                {   JOptionPane.showMessageDialog(null, e.getMessage());
                }
                break;
            }
        }
        else if (cmb_type.getSelectedIndex() == 2) //Staff
        {
            String sql = null;
            if ((txt_id == null || txt_id.getText().trim().isEmpty()) && (txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                sql="Select * from staff"; option=1;
            }
            else if (!(txt_id == null || txt_id.getText().trim().isEmpty()) && (txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                sql="Select * from staff where StaffID='"+txt_id.getText()+"'"; option=1;
            }
            else if ((txt_id == null || txt_id.getText().trim().isEmpty()) && !(txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                sql="Select * from staff where SNIC='"+txt_nic.getText()+"'"; option=1;
            }
            else //if (!(txt_id == null || txt_id.getText().trim().isEmpty()) && !(txt_nic == null || txt_nic.getText().trim().isEmpty()))
            {
                JOptionPane.showMessageDialog(null,"Enter Staff ID or NIC to view details");
            }
            switch (option)
            {
                case 0:
                break;

                case 1:
                try
                {   ResultSet rs;
                    CAdminStaffDetails ASdetails=new CAdminStaffDetails();
                    rs=ASdetails.getDetails(sql);
                    while(rs.next())
                    {
                        String id=rs.getString("StaffID");
                        //String full_name=rs.getString("CFullname");
                        String initial_name=rs.getString("SIniName");
                        String nic=rs.getString("SNIC");
                        String gender=rs.getString("SGender");
                        String dob=rs.getString("SDOB");
                        //String age=String.valueOf(rs.getInt("Age"));
                        String address=rs.getString("StaffAddress");
                        String tp_number=String.valueOf(rs.getInt("StaffTP"));
                        String email=rs.getString("StaffEmail");

                        String tbData[]={id,initial_name,nic,gender,dob,address,tp_number,email};
                        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                        tblModel.addRow(tbData);
                    }

                }
                catch (SQLException e)
                {   JOptionPane.showMessageDialog(null, e.getMessage());
                }
                catch (Exception e)
                {   JOptionPane.showMessageDialog(null, e.getMessage());
                }
                break;
            }
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        cmb_type.setSelectedIndex(0);
        txt_id.setText("");
        txt_nic.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        try{
            int result;
            FileReader reader1 = new FileReader("UserDetails.txt");
            while ((result=reader1.read())!=-1)
            {   String id;
                id=String.valueOf(result);
                char code=id.charAt(0);
                if(code=='6')
                {   
                    VAdminDashboard adash = new VAdminDashboard();
                    adash.show();
                    this.dispose();

                }
                else
                {
                    VStaffDashboard adash = new VStaffDashboard();
                    adash.show();
                    this.dispose();
                }
                break;
            }
        }

        catch(FileNotFoundException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(IOException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_back2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdminStaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdminStaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdminStaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdminStaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdminStaffDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_view;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_back1;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
