/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CAddCustomer;
import static View.VAddAdminStaff.emailValidator;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VCustomerAdd extends javax.swing.JFrame {

    /**
     * Creates new form VCustomerAdd
     */
    public VCustomerAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_cid = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_ininame = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_tp = new javax.swing.JTextField();
        txt_aid = new javax.swing.JTextField();
        txt_deposit = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        cmb_gender = new javax.swing.JComboBox<>();
        cmb_type = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Customer");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 328, 28));

        txt_fname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fnameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 328, 30));

        txt_ininame.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_ininame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 318, 30));

        txt_dob.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 328, 32));

        txt_age.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 328, 32));

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 328, 29));

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 323, 28));

        txt_tp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 323, 28));

        txt_aid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_aid.setText("2000");
        jPanel1.add(txt_aid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 323, 32));

        txt_deposit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 323, 32));

        txt_nic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 323, 29));

        cmb_gender.setBackground(new java.awt.Color(204, 0, 0));
        cmb_gender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmb_gender.setForeground(new java.awt.Color(255, 255, 255));
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(cmb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 328, 28));

        cmb_type.setBackground(new java.awt.Color(204, 0, 0));
        cmb_type.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmb_type.setForeground(new java.awt.Color(255, 255, 255));
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Account tpye", "Children Saving Account", "Youth Saving Account", "Senior Citizen Saving Account" }));
        jPanel1.add(cmb_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 323, 33));

        btn_save.setBackground(new java.awt.Color(204, 0, 0));
        btn_save.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, 133, 44));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Customer ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name With Initials");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date Of Birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("NIC Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Email ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Telephone Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Account Type");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Account ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Frist Deposit");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 660, 124, 44));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add Customer");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        lbl_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_back.setText("<< Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyPressed

    }//GEN-LAST:event_txt_fnameKeyPressed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        //        String customerid=txt_cid.getText();
        //        String customerfullname=txt_fname.getText();
        //        String customerininame=txt_ininame.getText();
        //        String customerdob=txt_dob.getText();
        //        int customerage=Integer.parseInt(txt_age.getText());
        //        String customergender=(String) cmb_gender.getSelectedItem();
        //        String customernic=txt_nic.getText();
        //        String customeraddress=txt_address.getText();
        //        int customertp=Integer.parseInt(txt_tp.getText());
        //        String customeremail=txt_email.getText();
        //        String accountid=txt_aid.getText();
        //        String accounttype=(String) cmb_type.getSelectedItem();
        //        String firstdeposit=txt_deposit.getText();

        if(txt_cid.getText().equals("")&&txt_fname.getText().equals("")&&txt_ininame.getText().equals("")&&txt_age.getText().equals("")
            &&txt_nic.getText().equals("")&&txt_address.getText().equals("")&&cmb_type.getSelectedItem().equals('0')
            &&txt_email.getText().equals("")&&txt_aid.getText().equals("")||txt_cid.getText().equals("")&&txt_cid.getText().equals("")
            &&txt_deposit.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Details");
        }

        else if(txt_cid.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Customer Id Cannot Blank");
        }
        else if(txt_fname.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Full Name cannot be blank");
        }
        else if(txt_ininame.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Name With Initials cannot be blank");
        }
        else if(txt_fname.getText().matches("[0-9]+") || txt_ininame.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Full Name & Name With Initials cannot have numbers");
        }
        else if(txt_dob.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Date Of Birth Cannot Blank Correct Format YYYY-MM-DD");
        }
        else if(txt_age.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Age cannot be blank");
        }
        else if(!txt_age.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Age should be numeric only");
        }
        else if(cmb_gender.getSelectedIndex()==0)
        {JOptionPane.showMessageDialog(null,"Please Select Correct Gender","Error",0);
        }
        else if(txt_nic.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"NIC cannot be blank");
        }
        else if(txt_email.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter Email Address");
        }
        else if(!emailValidator(txt_email.getText())==true)
        {   JOptionPane.showMessageDialog(null,"Enter a valid email. Ex:name@gmail.com");
        }
        else if(txt_address.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Address cannot be blank");
        }
        else if(txt_tp.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Phone number cannot be blank");
        }
        else if(!txt_tp.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Phone number should be numeric only");
        }
        else if(txt_tp.getText().length()<10 || txt_tp.getText().length()>10)
        {   JOptionPane.showMessageDialog(null,"Phone number should have 10 numbers");
        }
        else if(cmb_type.getSelectedIndex()==0)
        {JOptionPane.showMessageDialog(null,"Please Select Account Type","Error",0);
        }
        else if(txt_aid.getText().equals("")||txt_aid.getText().equals("2000"))
        {   JOptionPane.showMessageDialog(null,"Check Accouny Id");
        }
        else if(txt_deposit.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter Deposit value");
        }

        else
        {
            String customerid;
            String customerfullname;
            String customerininame;
            String customerdob;
            int customerage;
            String customergender;
            String customernic;
            String customeraddress;
            int customertp;
            String customeremail;
            String accountid;
            String accounttype;
            String firstdeposit;

            customerid=txt_cid.getText().toString();
            customerfullname=txt_fname.getText().toString();
            customerininame=txt_ininame.getText().toString();
            customerdob=txt_dob.getText().toString();
            customerage=Integer.parseInt(txt_age.getText().toString());
            customergender=(String) cmb_gender.getSelectedItem().toString();
            customernic=txt_nic.getText().toString();
            customeraddress=txt_address.getText().toString();
            customertp=Integer.parseInt(txt_tp.getText().toString());
            customeremail=txt_email.getText().toString();
            accountid=txt_aid.getText().toString();
            accounttype=(String) cmb_type.getSelectedItem().toString();
            firstdeposit=txt_deposit.getText().toString();

            CAddCustomer cm=new CAddCustomer();
            cm.saveMemberData(customerid,customerfullname,customerininame,customerdob,customerage,customergender,customernic,customeraddress,customertp,customeremail,accountid,accounttype,firstdeposit);

        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed

        txt_fname.setText("");
        txt_ininame.setText("");
        txt_address.setText("");
        txt_dob.setText("");
        txt_age.setText("");
        txt_tp.setText("");
        txt_email.setText("");
        txt_nic.setText("");
        cmb_gender.setSelectedIndex(0);
        txt_deposit.setText("");
        cmb_type.setSelectedIndex(0);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
       try{
		int result;
		FileReader reader1 = new FileReader("UserDetails.txt");
		while ((result=reader1.read())!=-1)
		{   String id;
                    id=String.valueOf(result);
                    char code=id.charAt(0);
                    if(code=='6')
                    {   
                        VAdminDashboard adash = new VAdminDashboard();
                        adash.show();
                        this.dispose();

                    }
                    else
                    {
                    VStaffDashboard adash = new VStaffDashboard();
                    adash.show();
                    this.dispose();
                    }
                        break;
		}
            }
		
		catch(FileNotFoundException e)
		{	JOptionPane.showMessageDialog(null, e.getMessage());
		}
		catch(IOException e)
		{	JOptionPane.showMessageDialog(null, e.getMessage());
		}
    }//GEN-LAST:event_lbl_backMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CAddCustomer onload_id = new CAddCustomer();
        txt_cid.setText(onload_id.getNextUserId());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCustomerAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_aid;
    private javax.swing.JTextField txt_cid;
    private javax.swing.JTextField txt_deposit;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_ininame;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
