/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CDeleteUser;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VDeleteAdminAndStaff extends javax.swing.JFrame {

    /**
     * Creates new form VDeleteAdminAndStaff
     */
    public VDeleteAdminAndStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_name_with_i = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_age = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_nic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text_gender = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text_phone_number = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        type_selector = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btn_delete_admin_and_staff = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text_full_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Admin & Staff");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("DELETE ADMIN AND STAFF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 510, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Name With Initials");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 150, -1));

        text_name_with_i.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_name_with_i.setToolTipText("Name With Initials");
        jPanel1.add(text_name_with_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 218, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 95, -1));

        text_age.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_age.setToolTipText("Age");
        jPanel1.add(text_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 218, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("NIC");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        text_nic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_nic.setToolTipText("NIC");
        jPanel1.add(text_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 218, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Gender");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 95, -1));

        text_gender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_gender.setToolTipText("Gender");
        jPanel1.add(text_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 218, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Telephone Number");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));

        text_phone_number.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_phone_number.setToolTipText("Telephone Number");
        jPanel1.add(text_phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 218, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Email");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 95, -1));

        text_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_email.setToolTipText("Email");
        jPanel1.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 218, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("User Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 95, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("User Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 160, -1));

        text_id.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_id.setToolTipText("user id");
        text_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_idKeyReleased(evt);
            }
        });
        jPanel1.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 218, -1));

        type_selector.setBackground(new java.awt.Color(204, 0, 0));
        type_selector.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        type_selector.setForeground(new java.awt.Color(255, 255, 255));
        type_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "staff" }));
        jPanel1.add(type_selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 218, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("User Id");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 95, -1));

        btn_delete_admin_and_staff.setBackground(new java.awt.Color(204, 0, 0));
        btn_delete_admin_and_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_delete_admin_and_staff.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_admin_and_staff.setText("Delete");
        btn_delete_admin_and_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_admin_and_staffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete_admin_and_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 146, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Full Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 95, -1));

        text_full_name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_full_name.setToolTipText("Full Name");
        jPanel1.add(text_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 218, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Address");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 70, -1));

        text_address.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        text_address.setToolTipText("Address");
        jPanel1.add(text_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 218, -1));

        lbl_back2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_back2.setText("<< Back");
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_idKeyReleased
        String user_type="";
        int selected_index_type = type_selector.getSelectedIndex();
        if(selected_index_type == 0)
        {
            user_type = "admin";
        }
        else if(selected_index_type == 1)
        {   user_type = "staff";
        }
        CDeleteUser cd = new CDeleteUser();
        ResultSet st;
        st = cd.getUserData(user_type,text_id.getText());
        try{
            while(st.next())
            {   text_full_name.setText(st.getString(2));
                text_name_with_i.setText(st.getString(3));
                text_nic.setText(st.getString(4));
                text_gender.setText(st.getString(5));
                text_age.setText(st.getString(7));
                text_address.setText(st.getString(8));
                text_phone_number.setText(st.getString(9));
                text_email.setText(st.getString(10));
            }
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_text_idKeyReleased

    private void btn_delete_admin_and_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_admin_and_staffActionPerformed
        if(text_id.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please enter a user ID ");
        }
        else
        {String user_type="";
            int selected_index_type = type_selector.getSelectedIndex();
            if(selected_index_type == 0)
            {
                user_type = "admin";
            }
            else if(selected_index_type == 1)
            {   user_type = "staff";
            }
            CDeleteUser cd = new CDeleteUser();
            cd.deleteUser(user_type,text_id.getText());

            text_address.setText("");
            text_age.setText("");
            text_email.setText("");
            text_full_name.setText("");
            text_gender.setText("");
            text_id.setText("");
            text_name_with_i.setText("");
            text_nic.setText("");
            text_phone_number.setText("");
        }
    }//GEN-LAST:event_btn_delete_admin_and_staffActionPerformed

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        try{
            int result;
            FileReader reader1 = new FileReader("UserDetails.txt");
            while ((result=reader1.read())!=-1)
            {   String id;
                id=String.valueOf(result);
                char code=id.charAt(0);
                if(code=='6')
                {   
                    VAdminDashboard adash = new VAdminDashboard();
                    adash.show();
                    this.dispose();

                }
                else
                {
                    VStaffDashboard adash = new VStaffDashboard();
                    adash.show();
                    this.dispose();
                }
                break;
            }
        }

        catch(FileNotFoundException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(IOException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_back2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDeleteAdminAndStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDeleteAdminAndStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDeleteAdminAndStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDeleteAdminAndStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDeleteAdminAndStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_admin_and_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_age;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_full_name;
    private javax.swing.JTextField text_gender;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_name_with_i;
    private javax.swing.JTextField text_nic;
    private javax.swing.JTextField text_phone_number;
    private javax.swing.JComboBox<String> type_selector;
    // End of variables declaration//GEN-END:variables
}
