/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CUpdateUser;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VEditAdminStaff extends javax.swing.JFrame {

    /**
     * Creates new form VEditAdminStaff
     */
    public VEditAdminStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        txt_iname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_tp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Admin & Staff");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Name with Initials");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("NIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Date of Birth");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Mobile");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Password");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Age");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 50, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("User ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        txt_dob.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 280, -1));

        txt_age.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_age.setToolTipText("");
        jPanel1.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 260, -1));

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_id.setAutoscrolls(false);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 163, -1));

        btn_search.setBackground(new java.awt.Color(153, 153, 153));
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, 30));

        txt_iname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_iname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 270, -1));

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 760, -1));

        txt_fname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 280, -1));

        cmb_type.setBackground(new java.awt.Color(204, 0, 0));
        cmb_type.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmb_type.setForeground(new java.awt.Color(255, 255, 255));
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee Type", "admin", "staff" }));
        jPanel1.add(cmb_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Employe Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txt_nic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 280, -1));

        txt_tp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 280, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("EDIT STAFF AND  ADMIN");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 480, -1));

        cmb_gender.setBackground(new java.awt.Color(204, 0, 0));
        cmb_gender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmb_gender.setForeground(new java.awt.Color(255, 255, 255));
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(cmb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 60, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 260, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 280, -1));

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 146, 40));

        btn_update.setBackground(new java.awt.Color(204, 0, 0));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 159, 40));

        lbl_back2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_back2.setText("<< Back");
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        if(txt_id.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter UserID","Error",0);
        }
        else if(cmb_type.getSelectedIndex()==0)
        {JOptionPane.showMessageDialog(null,"Please Select User Type","Error",0);
        }
        else
        {
            String usertype="";
            int selectedtype = cmb_type.getSelectedIndex();
            if(selectedtype == 1)
            {   usertype="admin";
            }
            else if(selectedtype == 2)
            {   usertype="staff";
            }
            CUpdateUser x = new CUpdateUser();
            ResultSet rs;
            rs = x.getData(usertype,txt_id.getText());
            try
            {   while(rs.next())
                {   txt_fname.setText(rs.getString(2));
                    txt_iname.setText(rs.getString(3));
                    txt_nic.setText(rs.getString(4));
                    cmb_gender.setSelectedItem(rs.getString(5));
                    txt_dob.setText(rs.getString(6));
                    txt_age.setText(rs.getString(7));
                    txt_address.setText(rs.getString(8));
                    txt_tp.setText(rs.getString(9));
                    txt_email.setText(rs.getString(10));
                    txt_password.setText(rs.getString(11));
                }
            }
            catch(SQLException e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_id.setText("");
        txt_fname.setText("");
        txt_iname.setText("");
        txt_nic.setText("");
        cmb_type.setSelectedIndex(0);
        cmb_gender.setSelectedIndex(0);
        txt_dob.setText("");
        txt_age.setText("");
        txt_address.setText("");
        txt_tp.setText("");
        txt_email.setText("");
        txt_password.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String userid,fname,ininame,nic,gender,dob,age,address,tpno,email,password;
        String user_type="";
        int selected_index_type = cmb_type.getSelectedIndex();
        if(txt_id.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter UserID","Error",0);
        }
        else if(txt_fname.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Fill the First Name","Error",0);
        }
        else if(txt_fname.getText().matches("[0-9]+")|| txt_iname.getText().matches("[0-9]+"))
        {   JOptionPane.showMessageDialog(null,"Full Name & Name with Initials Cannot Have Numbers","Error",0);
        }
        else if(txt_iname.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Please Fill Name with Initials","Error",0);
        }
        else if(cmb_type.getSelectedIndex()==0)
        {JOptionPane.showMessageDialog(null,"Please Select User Type","Error",0);
        }
        else if(txt_address.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Please Fill Address","Error",0);
        }
        else if(txt_nic.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Please Fill NIC","Error",0);
        }
        else if(cmb_gender.getSelectedIndex()==0)
        {JOptionPane.showMessageDialog(null,"Please Select Gender","Error",0);
        }
        else if(txt_dob.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Date of Birth Cannot be Blank","Error",0);
        }
        else if(txt_age.getText().equals("")||txt_age.getText().matches("^[a-zA-Z]*$"))
        {JOptionPane.showMessageDialog(null,"Please Check the Age Again","Error",0);
        }
        else if(!txt_email.getText().matches("^(.+)@(.+)$"))
        {JOptionPane.showMessageDialog(null,"Please Check the Email Again","Error",0);
        }
        else if(txt_tp.getText().equals("")||txt_tp.getText().matches("^[a-zA-Z]*$"))
        {JOptionPane.showMessageDialog(null,"Please Check the Telephone Number Again","Error",0);
        }
        else if(txt_password.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Password Cannot be Blank","Error",0);
        }

        else
        {
            if(selected_index_type == 1)
            {
                user_type = "admin";
            }
            else if(selected_index_type == 2)
            {   user_type = "staff";
            }
            userid=txt_id.getText();
            fname=txt_fname.getText();
            ininame=txt_iname.getText();
            nic=txt_nic.getText();
            gender=(String)cmb_gender.getSelectedItem();
            dob=txt_dob.getText();
            age=txt_age.getText();
            address=txt_address.getText();
            email=txt_email.getText();
            password=txt_password.getText();
            tpno=txt_tp.getText();

            CUpdateUser ca=new CUpdateUser();
            ca.udateAdminData(user_type,userid,fname,ininame,nic,gender,dob,age,address,tpno,email,password);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        try{
            int result;
            FileReader reader1 = new FileReader("UserDetails.txt");
            while ((result=reader1.read())!=-1)
            {   String id;
                id=String.valueOf(result);
                char code=id.charAt(0);
                if(code=='6')
                {   
                    VAdminDashboard adash = new VAdminDashboard();
                    adash.show();
                    this.dispose();

                }
                else
                {
                    VStaffDashboard adash = new VStaffDashboard();
                    adash.show();
                    this.dispose();
                }
                break;
            }
        }

        catch(FileNotFoundException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(IOException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_back2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEditAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEditAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEditAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEditAdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEditAdminStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_iname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
