/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CPasswordChange;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VPasswordChange extends javax.swing.JFrame {

    /**
     * Creates new form VPasswordChange
     */
    public VPasswordChange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_usersid = new javax.swing.JTextField();
        txt_usersemail = new javax.swing.JTextField();
        txt_usersnic = new javax.swing.JTextField();
        btn_resetpw = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Reset");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Password Reset");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("User ID ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("NIC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        txt_usersid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_usersid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 260, -1));

        txt_usersemail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_usersemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 440, -1));

        txt_usersnic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_usersnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 260, -1));

        btn_resetpw.setBackground(new java.awt.Color(204, 0, 0));
        btn_resetpw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_resetpw.setForeground(new java.awt.Color(255, 255, 255));
        btn_resetpw.setText("Reset password");
        btn_resetpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetpwActionPerformed(evt);
            }
        });
        jPanel1.add(btn_resetpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 190, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("<<Back");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetpwActionPerformed
        String usersid,usersnic,usersemail;
        usersid=txt_usersid.getText();
        usersnic=txt_usersnic.getText();
        usersemail=txt_usersemail.getText();
if(txt_usersid.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Fill the Data First to Login","Error",0);
        }
        else if(txt_usersnic.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter User ID","Error",0);
        }
        else if(txt_usersemail.getText().equals(""))
        {   JOptionPane.showMessageDialog(null,"Please Enter Password","Error",0);
        }
else
        {
            CPasswordChange password = new CPasswordChange();
            ResultSet rs;
            rs = password.getData(usersid,usersnic,usersemail);
        }






    }//GEN-LAST:event_btn_resetpwActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        VLogin login = new VLogin();
        login.show();
        VPasswordChange pw= new VPasswordChange();
        pw.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPasswordChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_resetpw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_usersemail;
    private javax.swing.JTextField txt_usersid;
    private javax.swing.JTextField txt_usersnic;
    // End of variables declaration//GEN-END:variables
}
