/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VStaffDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VStaffDashboard
     */
    public VStaffDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_deletecus = new javax.swing.JButton();
        btn_viewtransactions = new javax.swing.JButton();
        btn_addcus = new javax.swing.JButton();
        btn_editcus = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_viewcus = new javax.swing.JButton();
        btn_transactions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\NIBM\\1st Year\\EAD\\EAD CW2 Redna Bank\\Redna_Bank\\src\\main\\java\\images\\logofordashboard.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Welcome Come to Redna Bank");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 560, 80));

        btn_deletecus.setBackground(new java.awt.Color(0, 0, 0));
        btn_deletecus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_deletecus.setForeground(new java.awt.Color(255, 255, 255));
        btn_deletecus.setText("Delete Account");
        btn_deletecus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deletecus, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 260, 70));

        btn_viewtransactions.setBackground(new java.awt.Color(0, 0, 0));
        btn_viewtransactions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_viewtransactions.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewtransactions.setText("View Transactions");
        btn_viewtransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewtransactionsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewtransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 260, 70));

        btn_addcus.setBackground(new java.awt.Color(0, 0, 0));
        btn_addcus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addcus.setForeground(new java.awt.Color(255, 255, 255));
        btn_addcus.setText("Add Customer");
        btn_addcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 260, 70));

        btn_editcus.setBackground(new java.awt.Color(0, 0, 0));
        btn_editcus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_editcus.setForeground(new java.awt.Color(255, 255, 255));
        btn_editcus.setText("Edit Customer");
        btn_editcus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editcusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 260, 70));

        btn_logout.setBackground(new java.awt.Color(204, 0, 0));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LogOut");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 150, 40));

        btn_viewcus.setBackground(new java.awt.Color(0, 0, 0));
        btn_viewcus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_viewcus.setForeground(new java.awt.Color(255, 255, 255));
        btn_viewcus.setText("View Customer");
        btn_viewcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewcusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 260, 70));

        btn_transactions.setBackground(new java.awt.Color(0, 0, 0));
        btn_transactions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_transactions.setForeground(new java.awt.Color(255, 255, 255));
        btn_transactions.setText("Transactions");
        btn_transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transactionsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 260, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\NIBM\\1st Year\\EAD\\EAD CW2 Redna Bank\\Redna_Bank\\src\\main\\java\\images\\Homebackpic.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deletecusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletecusActionPerformed
        VDeleteAccount va = new VDeleteAccount();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_deletecusActionPerformed

    private void btn_viewtransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewtransactionsActionPerformed
        VTransactionDetails va = new VTransactionDetails();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_viewtransactionsActionPerformed

    private void btn_addcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcusActionPerformed
        VCustomerAdd va = new VCustomerAdd();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_addcusActionPerformed

    private void btn_editcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editcusActionPerformed
        VUpdateCustomer va = new VUpdateCustomer();
        va.show();
        this.dispose();
    }//GEN-LAST:event_btn_editcusActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        VLogin l = new VLogin();
        l.show();
        this.dispose();
                    try
                    {
                        char data[]={};
                        FileWriter ft = new FileWriter("UserDetails.txt");
                        ft.write(data);
                        ft.close();
                    }
                    catch(FileNotFoundException ex)
                    {     JOptionPane.showMessageDialog(null,ex.getMessage());  
                    }
                    catch(IOException ex)
                    {       JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_viewcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewcusActionPerformed
        VCustomerDetails vt = new VCustomerDetails();
        vt.show();
        this.dispose();
    }//GEN-LAST:event_btn_viewcusActionPerformed

    private void btn_transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transactionsActionPerformed
        VTransaction vt = new VTransaction();
        vt.show();
        this.dispose();
    }//GEN-LAST:event_btn_transactionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VStaffDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcus;
    private javax.swing.JButton btn_deletecus;
    private javax.swing.JButton btn_editcus;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_transactions;
    private javax.swing.JButton btn_viewcus;
    private javax.swing.JButton btn_viewtransactions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
