/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CTransaction;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VTransaction extends javax.swing.JFrame {

    /**
     * Creates new form VTransaction
     */
    public VTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_AccountIdSearch = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_depositAmount = new javax.swing.JTextField();
        btn_deposit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_withdrawAmount = new javax.swing.JTextField();
        btn_withdraw = new javax.swing.JButton();
        txt_AccountNumber = new javax.swing.JTextField();
        txt_CustomerId = new javax.swing.JTextField();
        txt_AccountType = new javax.swing.JTextField();
        txt_AccountBalance = new javax.swing.JTextField();
        btn_clearSearchID = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmb_accountType = new javax.swing.JComboBox<>();
        txt_interest = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_addInterest = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_back2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transactions");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_AccountIdSearch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_AccountIdSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 197, 33));

        btn_Search.setBackground(new java.awt.Color(204, 0, 0));
        btn_Search.setForeground(new java.awt.Color(255, 255, 255));
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 121, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Account Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Account Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Account Balance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEPOSIT");

        txt_depositAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btn_deposit.setBackground(new java.awt.Color(255, 255, 255));
        btn_deposit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_deposit.setText("Deposit");
        btn_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_depositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_deposit)
                                .addGap(44, 44, 44))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(txt_depositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btn_deposit)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WITHDRAW");

        txt_withdrawAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btn_withdraw.setBackground(new java.awt.Color(255, 255, 255));
        btn_withdraw.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_withdraw.setText("Withdraw");
        btn_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_withdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(txt_withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_withdraw)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(txt_withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_withdraw)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        txt_AccountNumber.setEditable(false);
        txt_AccountNumber.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_AccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 231, -1));

        txt_CustomerId.setEditable(false);
        txt_CustomerId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_CustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 231, -1));

        txt_AccountType.setEditable(false);
        txt_AccountType.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 231, -1));

        txt_AccountBalance.setEditable(false);
        txt_AccountBalance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txt_AccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 231, -1));

        btn_clearSearchID.setBackground(new java.awt.Color(153, 153, 153));
        btn_clearSearchID.setText("Clear");
        btn_clearSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSearchIDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clearSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 121, 33));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Add Interest to Bank Accounts");

        cmb_accountType.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmb_accountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account Type", "Children Savings Account", "Youth Savings Account", "Senior Citizen Savings Account" }));

        txt_interest.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Interest");

        btn_addInterest.setBackground(new java.awt.Color(255, 255, 255));
        btn_addInterest.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_addInterest.setText("Add");
        btn_addInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addInterestActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cmb_accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(txt_interest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(btn_addInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel8)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addInterest)
                    .addComponent(btn_clear))
                .addGap(38, 38, 38))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("TRANSACTIONS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 310, -1));

        lbl_back2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_back2.setText("<< Back");
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
        });
        jPanel1.add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Account Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        if(txt_AccountIdSearch == null || (txt_AccountIdSearch.getText()).trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Account Number","Information",0);
        }
        else
        {
            try
            {
                String account_id=txt_AccountIdSearch.getText();
                ResultSet rs;
                CTransaction ctransac=new CTransaction();
                rs=ctransac.getAccountDetails(account_id);
                /*if(rs.next() == false) {
                    JOptionPane.showMessageDialog(null,"Account Number Does not exist","Error",0);
                }*/
                if(rs.next()) {
                    String AccID = rs.getString("AccountID");
                    txt_AccountNumber.setText(AccID);
                    String CusID = rs.getString("CusID");
                    txt_CustomerId.setText(CusID);
                    String AccType = rs.getString("AccType");
                    txt_AccountType.setText(AccType);
                    Float AccBalance = rs.getFloat("AccountBalance");
                    txt_AccountBalance.setText(String.valueOf(AccBalance));
                }
            }
            catch(SQLException e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositActionPerformed
        // TODO add your handling code here:
        if(txt_depositAmount == null || (txt_depositAmount.getText()).trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Deposit Amount","Information",0);
        }
        else if(!txt_depositAmount.getText().matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null,"Enter Numeric Values Only","Information",0);
        }
        else
        {
            try {
                ResultSet rsAmount;
                String account_id=txt_AccountNumber.getText();
                float deposit_amount=Float.parseFloat(txt_depositAmount.getText());
                CTransaction ctransac=new CTransaction();
                rsAmount=ctransac.depositMoney(account_id,deposit_amount);
                if(rsAmount.next()) {
                    Float AccBalance = rsAmount.getFloat("AccountBalance");
                    txt_AccountBalance.setText(String.valueOf(AccBalance));
                }
                txt_depositAmount.setText("");
            }
            catch(SQLException e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_depositActionPerformed

    private void btn_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_withdrawActionPerformed
        // TODO add your handling code here:
        if(txt_withdrawAmount == null || (txt_withdrawAmount.getText()).trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Withdraw Amount","Error",0);
        }
        else if(!txt_withdrawAmount.getText().matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null,"Enter Numeric Values Only","Error",0);
        }
        else if(Float.parseFloat(txt_withdrawAmount.getText())>Float.parseFloat(txt_AccountBalance.getText()))
        {   JOptionPane.showMessageDialog(null,"Insufficient Funds","Error",0);
        }
        else
        {
            try {
                ResultSet rsDAmount;
                String account_id=txt_AccountNumber.getText();
                float withdraw_amount=Float.parseFloat(txt_withdrawAmount.getText());
                CTransaction ctransac=new CTransaction();
                rsDAmount=ctransac.withdrawMoney(account_id, withdraw_amount);
                if(rsDAmount.next()) {
                    Float AccBalance=rsDAmount.getFloat("AccountBalance");
                    txt_AccountBalance.setText(String.valueOf(AccBalance));
                }
                txt_withdrawAmount.setText("");
            }
            catch (SQLException e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_withdrawActionPerformed

    private void btn_clearSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearSearchIDActionPerformed
        // TODO add your handling code here:
        txt_AccountIdSearch.setText("");
        txt_AccountNumber.setText("");
        txt_CustomerId.setText("");
        txt_AccountType.setText("");
        txt_AccountBalance.setText("");
    }//GEN-LAST:event_btn_clearSearchIDActionPerformed

    private void btn_addInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addInterestActionPerformed
        // TODO add your handling code here:
        CTransaction ctransac=new CTransaction();

        if(txt_interest == null || txt_interest.getText().trim().isEmpty())
        {   JOptionPane.showMessageDialog(null,"Enter Interest","Error",0);
        }
        else if(cmb_accountType.getSelectedIndex() == 0)
        {   JOptionPane.showMessageDialog(null,"Select the Account Type","Error",0);
        }
        else if(!txt_interest.getText().matches("[0-9].[0-9]+"))
        {   JOptionPane.showMessageDialog(null, "Enter Numeric Value Only","Error",0);
        }
        else
        {
            float interest=Float.parseFloat(txt_interest.getText());
            if (cmb_accountType.getSelectedIndex() == 1) //Childrens Savings Account
            {   String account_type="Childrens Saving Account";
                ctransac.addInterest(account_type,interest );
            }
            else if (cmb_accountType.getSelectedIndex() == 2) //Youth Savings Account
            {   String account_type="Youth Saving Account";
                ctransac.addInterest(account_type, interest);
            }
            else if (cmb_accountType.getSelectedIndex() == 3) //Senior Citizen Savings Account
            {   String account_type="Senior Citizen Saving Account";
                ctransac.addInterest(account_type, interest);
            }
        }
    }//GEN-LAST:event_btn_addInterestActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_interest.setText("");
        cmb_accountType.setSelectedIndex(0);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        try{
            int result;
            FileReader reader1 = new FileReader("UserDetails.txt");
            while ((result=reader1.read())!=-1)
            {   String id;
                id=String.valueOf(result);
                char code=id.charAt(0);
                if(code=='6')
                {   
                    VAdminDashboard adash = new VAdminDashboard();
                    adash.show();
                    this.dispose();

                }
                else
                {
                    VStaffDashboard adash = new VStaffDashboard();
                    adash.show();
                    this.dispose();
                }
                break;
            }
        }

        catch(FileNotFoundException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(IOException e)
        {	JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_back2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_addInterest;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clearSearchID;
    private javax.swing.JButton btn_deposit;
    private javax.swing.JButton btn_withdraw;
    private javax.swing.JComboBox<String> cmb_accountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JTextField txt_AccountBalance;
    private javax.swing.JTextField txt_AccountIdSearch;
    private javax.swing.JTextField txt_AccountNumber;
    private javax.swing.JTextField txt_AccountType;
    private javax.swing.JTextField txt_CustomerId;
    private javax.swing.JTextField txt_depositAmount;
    private javax.swing.JTextField txt_interest;
    private javax.swing.JTextField txt_withdrawAmount;
    // End of variables declaration//GEN-END:variables
}
